### PR TITLE
Fix missing displayName field in Google Drive source indexing

### LINKED ISSUE #67: Google Drive source file processing fails due to missing lastModifyingUser.displayName field
The following access to the `lastModifyingUser.displayName` field fails
https://github.com/GerevAI/gerev/blob/20d0245aaaf546ee15e91b76a67499d3ab13a7f6/app/data_sources/google_drive.py#L183

```
2023-03-27 10:05:46,340 | INFO | google_drive.py:140 | processing file ********************
2023-03-27 10:05:47,523 | ERROR | base_data_source.py:95 | Error while indexing data source
Traceback (most recent call last):
  File "/app/data_source_api/base_data_source.py", line 93, in index
    self._feed_new_documents()
  File "/app/data_sources/google_drive.py", line 199, in _feed_new_documents
    self._index_files_from_drive(drive)
  File "/app/data_sources/google_drive.py", line 183, in _index_files_from_drive
     author=file['lastModifyingUser']['displayName'],
KeyError: 'displayName'
```

Google's [documentation](https://developers.google.com/drive/api/v3/reference/files) DOES NOT mention that it may not be defined, but it was for me:
`lastModifyingUser.displayName    string    A plain text displayable name for this user.`

It is probably related to a user in a shared Google workspace that was deleted.

### PR DESCRIPTION
**Pull request by teynar**
fixes #67

### CODE REVIEW

**Comment by Roey7** [comment]
Can you check if there is any other `author` to provide in such scenario?

**Comment by teynar** [comment]
> Can you check if there is any other `author` to provide in such scenario?

One option would be to use one of the owners of the file via `owners[].displayName` or all or their names separated by commas

**Comment by Roey7** [comment]
@teynar aight `owners[0].displayName` sounds ok

**Comment by Roey7** [comment]
thanks :)

**Pull request merged**
